import { useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { Archive, Download } from 'lucide-react';
import PageLayout from '../components/ui/PageLayout';
import QueryError from '../components/ui/QueryError';
import { request, downloadBackup } from '../utils/operations';

type Backup = { name: string; created_at: string; size: number; counts: Record<string, number> };
type Preview = { token: string; created_at: string; notice: string; tables: { table: string; current: number; backup: number; added: number; removed: number; changed: number }[] };
export default function BackupsPage() {
  const [password, setPassword] = useState(''); const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<Preview | null>(null); const [notice, setNotice] = useState('');
  const query = useQuery({ queryKey: ['backups'], queryFn: () => request<Backup[]>('/api/v1/operations/backups') });
  const create = useMutation({ mutationFn: () => request<Backup>('/api/v1/operations/backups', { password }), onSuccess: async data => { setNotice('Копия создана. Сохраните пароль отдельно: без него восстановление невозможно.'); await query.refetch(); await downloadBackup(data.name); setPassword(''); }, onError: e => setNotice(e.message) });
  const inspect = useMutation({ mutationFn: async () => { if (!file || file.size > 20 * 1024 ** 2) throw new Error('Выберите копию размером до 20 МБ'); const data = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(',')[1]); reader.onerror = () => reject(new Error('Не удалось прочитать файл')); reader.readAsDataURL(file); }); return request<Preview>('/api/v1/operations/restore/preview', { data, password }); }, onSuccess: setPreview, onError: e => setNotice(e.message) });
  const restore = useMutation({ mutationFn: () => request<{ rollback_copy: string }>('/api/v1/operations/restore', { token: preview?.token, confirm: true, password }), onSuccess: data => { setPreview(null); setPassword(''); setNotice('Копия восстановлена. Предыдущее состояние сохранено в ' + data.rollback_copy + '. Обновите страницу.'); query.refetch(); }, onError: e => setNotice(e.message) });
  const busy = create.isPending || inspect.isPending || restore.isPending;
  return <PageLayout title="Резервные копии" description="Зашифрованные копии клиентов, профилей, нод, маршрутов и настроек этой установки" icon={Archive}>
    <section className="ui-card ui-panel space-y-4"><p className="text-sm text-neutral-600">Копия содержит настройки и данные подключения. Она защищена вашим паролем и восстанавливается в этой же установке. Системные файлы, сертификаты и учётная запись администратора в копию не входят. Для восстановления нужен исходный JWT_SECRET_KEY: сохраните файл .env отдельно. Копии лежат на том же диске сервера; скачивайте их на другое устройство.</p><label className="block text-sm">Пароль копии — минимум 12 символов<input autoComplete="new-password" type="password" minLength={12} maxLength={256} className="mt-2 w-full border p-3" value={password} onChange={e => { setPassword(e.target.value); setPreview(null); }} /></label><button className="ui-button ui-button-primary" disabled={busy || password.length < 12} onClick={() => { setNotice(''); create.mutate(); }}>{create.isPending ? 'Создаём…' : 'Создать и скачать копию'}</button><p role="status" className="text-sm text-neutral-600">{notice}</p></section>
    <section className="ui-card ui-panel"><h2 className="ui-card-title mb-4">Сохранённые копии</h2>{query.error && <QueryError error={query.error} retry={() => query.refetch()} />}{query.isLoading ? <p>Загрузка…</p> : query.data?.length ? query.data.map(b => <div key={b.name} className="flex flex-wrap items-center justify-between gap-3 border-b border-neutral-100 py-3"><div><p className="text-sm">{new Date(b.created_at).toLocaleString('ru')}</p><p className="text-xs text-neutral-500">{Math.ceil(b.size / 1024)} КБ · Клиентов: {b.counts.clients} · Нод: {b.counts.nodes}</p></div><button className="ui-button ui-button-secondary" onClick={() => downloadBackup(b.name).catch(e => setNotice(e.message))}><Download size={16} />Скачать</button></div>) : !query.error && <p className="text-sm text-neutral-500">Копий пока нет</p>}</section>
    <section className="ui-card ui-panel space-y-4"><h2 className="ui-card-title">Восстановление</h2><input type="file" accept=".mdbackup" disabled={busy} onChange={e => { setFile(e.target.files?.[0] || null); setPreview(null); }} /><p className="text-sm text-neutral-500">Введите пароль выбранной копии в поле выше. Перед применением будет создана копия текущего состояния с этим же паролем.</p><button className="ui-button ui-button-secondary" disabled={busy || !file || password.length < 12} onClick={() => { setNotice(''); inspect.mutate(); }}>{inspect.isPending ? 'Проверяем…' : 'Проверить состав копии'}</button>
      {preview && <div className="space-y-4 rounded-xl border border-amber-200 p-4"><p className="text-sm text-amber-800">{preview.notice} Привязки Telegram будут отозваны.</p><p className="text-sm">Дата копии: {new Date(preview.created_at).toLocaleString('ru')}</p><table><thead><tr><th>Данные</th><th>Сейчас</th><th>В копии</th><th>Изменения</th></tr></thead><tbody>{preview.tables.map(t => <tr key={t.table}><td>{({ nodes: 'Ноды', clients: 'Клиенты', client_profiles: 'Профили', routing_rules: 'Правила', settings: 'Настройки' })[t.table as 'nodes'] || t.table}</td><td>{t.current}</td><td>{t.backup}</td><td>+{t.added} / −{t.removed} / изменено {t.changed}</td></tr>)}</tbody></table><button className="ui-button ui-button-danger" disabled={busy} onClick={() => { if (window.confirm('Заменить данные панели выбранной копией?')) restore.mutate(); }}>{restore.isPending ? 'Восстанавливаем…' : 'Подтвердить восстановление'}</button></div>}
    </section>
  </PageLayout>;
}
